@extends('layouts.quality')
@section('content')
<x-portal-page title="Reportes de calidad" description="Concentrado institucional para consulta y preparación de informes.">
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-quality-stat label="Evidencias" :value="$evidences['total']" detail="Expedientes registrados"/><x-quality-stat label="Validadas" :value="$evidences['validadas']" detail="Listas para reporte" tone="emerald"/><x-quality-stat label="Pendientes" :value="$evidences['pendientes']" detail="En proceso de revisión" tone="amber"/><x-quality-stat label="Constancias" :value="$certificates['total']" detail="Resultados documentados" tone="slate"/></div>
    <div class="mt-6 grid gap-6 xl:grid-cols-[1.25fr_1fr]">
        <section class="overflow-hidden rounded-xl border border-slate-200"><div class="border-b border-slate-200 bg-slate-50 px-5 py-4"><h2 class="font-semibold">Reportes disponibles</h2><p class="mt-1 text-xs text-slate-500">Ejemplos de cortes institucionales</p></div><div class="divide-y divide-slate-100">@foreach([['Resumen de evidencias','Estatus y distribución de expedientes académicos','Actualizado hoy'],['Cumplimiento de acreditación','Concentrado CACEI, ABET e ISO','Corte agosto 2026'],['Resultados de evaluación','Aprobación y desempeño por actividad','Ciclo 2025–2026'],['Seguimiento de mejora','Avance y vencimiento de planes de acción','Actualizado hoy']] as $report)<article class="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="font-semibold text-slate-900">{{ $report[0] }}</h3><p class="mt-1 text-sm text-slate-500">{{ $report[1] }}</p><p class="mt-2 text-xs font-medium text-blue-600">{{ $report[2] }}</p></div><button class="shrink-0 rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700 transition hover:border-blue-400 hover:text-blue-700" type="button">Ver reporte</button></article>@endforeach</div></section>
        <aside class="space-y-6"><section class="rounded-xl border border-slate-200 p-5"><h2 class="font-semibold">Distribución de evidencias</h2><div class="mt-5 space-y-5">@php($total = max(1, $evidences['total']))<x-quality-progress label="Validadas" :value="round($evidences['validadas'] / $total * 100)" :detail="$evidences['validadas'].' expedientes'" tone="emerald"/><x-quality-progress label="Pendientes" :value="round($evidences['pendientes'] / $total * 100)" :detail="$evidences['pendientes'].' expedientes'" tone="amber"/><x-quality-progress label="Rechazadas" :value="round($evidences['rechazadas'] / $total * 100)" :detail="$evidences['rechazadas'].' expedientes'" tone="rose"/></div></section><section class="rounded-xl bg-slate-900 p-5 text-white"><p class="text-xs font-bold uppercase tracking-wider text-blue-300">Próximo corte</p><p class="mt-2 text-2xl font-bold">31 de agosto</p><p class="mt-2 text-sm text-slate-300">Consolida las evidencias pendientes antes de generar el informe mensual.</p></section></aside>
    </div>
</x-portal-page>
@endsection
